version: '3'
services:
  nginx:
    container_name: club-plein-air-altitude_nginx
    privileged: true
    image: docker.gitlab.libeo.com/docker/nginx:1.15-fpm
    environment:
      CURRENT_UID: ${CURRENT_UID}
      SERVER_ROOT: /var/www/public
      PHP_FPM_HOST: php-fpm
    depends_on:
      - php-fpm
    volumes:
      - ../src/:/var/www
    labels:
      - "traefik.docker.network=traefik_default"
      - "traefik.frontend.rule=Host:club-plein-air-altitude.local.vici.io"
    networks:
      - traefik_default
      - backend
  php-fpm:
    container_name: club-plein-air-altitude_php-fpm
    image: docker.gitlab.libeo.com/docker/php:7.3-fpm
    environment:
      CURRENT_UID: ${CURRENT_UID}
      MEMORY_LIMIT: '512M'
    volumes:
      - ../src/:/var/www
    depends_on:
      - mysql
      - memcached
      - maildev
    networks:
      backend:
        aliases:
          - php-fpm
  mysql:
    container_name: club-plein-air-altitude_mysql
    image: mysql:5.7
    command:
      - --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: statut
      MYSQL_USER: statut
      MYSQL_PASSWORD: statut
      MYSQL_DATABASE: statut
    volumes:
      - mysql:/var/lib/mysql
    networks:
      backend:
        aliases:
          - mysql
  maildev:
    container_name: club-plein-air-altitude_maildev
    image: djfarrelly/maildev
    labels:
      - "traefik.docker.network=traefik_default"
      - "traefik.frontend.rule=Host:mail.club-plein-air-altitude.local.vici.io"
      - "traefik.port=80"
    networks:
      traefik_default:
      backend:
        aliases:
          - maildev
  memcached:
    container_name: club-plein-air-altitude_memcached
    image: memcached
    networks:
      backend:
        aliases:
          - memcached

networks:
  backend:
  traefik_default:
    external: true
volumes:
  mysql:
